#!/usr/bin/env python3
# ai-processed:unverified · session:6ab1c2ae-25dd-40bf-9ca2-05072ee58b83 · 2026-06-28
# backfill-provenance v2 / tests. Run directly: python3 tests/test_v2.py
# Covers DESIGN §5.2 replay fixtures, the CLAUDE.md mixed-authorship trap (§2.4a),
# the inversion two-signal gate (§2.6), Bash analysis (§2.1), apply_patch (§2.5),
# marker round-trip + reconciliation (§7, §10), secret quarantine (§7.1).

import os
import sys
import tempfile
import hashlib

HERE = os.path.dirname(os.path.abspath(__file__))
SKILL = os.path.dirname(HERE)
sys.path.insert(0, SKILL)
sys.path.insert(0, os.path.join(SKILL, "lib"))

from pv_backfill import adapters, graph, classify, report, mark
import provenance

PASS = []
FAIL = []


def check(name, cond):
    (PASS if cond else FAIL).append(name)
    print(f"  {'PASS' if cond else 'FAIL'}  {name}")


def sha(s):
    return hashlib.sha256(s.encode()).hexdigest()


# ---------------------------------------------------------------------------
print("\n[replay fixtures — DESIGN §5.2]")
check("edit first-match (replace_all=False)",
      graph.apply_edit("a x a", "a", "B", False) == "B x a")
check("edit replace_all=True",
      graph.apply_edit("a x a", "a", "B", True) == "B x B")
check("edit empty replacement",
      graph.apply_edit("hello", "llo", "", False) == "he")
try:
    graph.apply_edit("abc", "zzz", "q")
    check("edit missing match -> abstain", False)
except graph.ReplayError:
    check("edit missing match -> abstain", True)
check("edit CRLF/LF tolerance (LF old_string matches CRLF file)",
      graph.apply_edit("foo\r\nbar", "foo\nbar", "BAZ") == "BAZ")
check("multiedit atomic ordered chain",
      graph.apply_multiedit("1 2 3", [{"old": "1", "new": "A", "replace_all": False},
                                      {"old": "3", "new": "C", "replace_all": False}]) == "A 2 C")
try:
    graph.apply_multiedit("1 2 3", [{"old": "1", "new": "A"}, {"old": "ZZ", "new": "C"}])
    check("multiedit fails whole chain on any miss", False)
except graph.ReplayError:
    check("multiedit fails whole chain on any miss", True)

print("\n[apply_patch parsing/replay — DESIGN §2.5]")
patch_add = "*** Begin Patch\n*** Add File: foo.py\n+print('hi')\n+x = 1\n*** End Patch"
secs = list(adapters.parse_apply_patch(patch_add))
check("apply_patch Add carries full body",
      secs and secs[0][0] == "add" and secs[0][2] == "print('hi')\nx = 1\n")
upd = "*** Update File: foo.py\n@@\n print('hi')\n-x = 1\n+x = 2\n"
secs = list(adapters.parse_apply_patch(upd))
base = "print('hi')\nx = 1\n"
try:
    res = graph.apply_patch_update(base, secs[0][2])
    check("apply_patch Update replays to expected", res == "print('hi')\nx = 2\n")
except graph.ReplayError:
    check("apply_patch Update replays to expected", False)

print("\n[Bash analysis — DESIGN §2.1]")
eligible = analyze = adapters.analyze_bash(
    "cd \"/tmp/x\"\nmkdir -p /tmp/x\ncat > /tmp/x/out.md <<'EOF'\nhello\nworld\nEOF")
check("single quoted-delim heredoc -> eligible create",
      any(k == "create" and "hello\nworld" in d["body"] for k, d in eligible))
unsafe = adapters.analyze_bash("for f in *; do cat > $f <<'EOF'\nx\nEOF\ndone")
check("heredoc in loop/var -> NOT eligible (indirect)",
      all(k != "create" for k, d in unsafe))
redir = adapters.analyze_bash("python3 gen.py > out.py")
check("redirection -> indirect, never create",
      all(k != "create" for k, d in redir))
mv = adapters.analyze_bash("mv old.md new.md")
check("mv -> move edge", any(k == "move" for k, d in mv))


# ---------------------------------------------------------------------------
print("\n[end-to-end on a temp tree — CLAUDE.md trap + inversion gate]")
tmp = tempfile.mkdtemp(prefix="pv2test_", dir=os.path.join(SKILL, "tests"))
# The temp tree sits inside this repo's .git, so force the VCS branch explicitly per test
# to exercise both gate paths (DESIGN §2.6). Recent timestamps so the mtime window holds.
import time as _time
NOW_ISO = _time.strftime("%Y-%m-%dT%H:%M:%SZ", _time.gmtime())
classify._git_cache.clear()
_real_in_vcs = classify.in_vcs
classify.in_vcs = lambda p: False   # default: treat as NON-git for the gate tests below

# (A) Pure AI creation, content unchanged on disk, NON-git, file-history corroborates -> MARK
ai_body = "# generated by AI\nvalue = 42\n"
ai_path = os.path.join(tmp, "ai_made.py")
open(ai_path, "w").write(ai_body)
# (B) Human file AI later EDITED (mixed authorship) -> must NOT be marked
human_body = "# human wrote this\nimportant = True\n"
human_path = os.path.join(tmp, "human_then_ai.py")
open(human_path, "w").write(human_body + "# ai appended a line\n")
# (C) AI created but file changed on disk since (diverged) -> report-only
div_path = os.path.join(tmp, "diverged.py")
open(div_path, "w").write("# totally different now\n")

events = [
    # A: Write of exactly the on-disk bytes
    adapters._event("claude", "sessA", "logA", NOW_ISO, 1, "create", "Write",
                    ai_path, body=ai_body, tuid="t1", success=True, eligible=True),
    # B: only an Edit on a human base (no creation root) -> mixed/edit_chain_missing_base
    adapters._event("claude", "sessB", "logB", NOW_ISO, 1, "edit", "Edit",
                    human_path, edits=[{"old": "important = True", "new": "important = True\n# ai appended a line",
                                        "replace_all": False}], tuid="t2", success=True, eligible=True),
    # C: Write whose body != current disk
    adapters._event("claude", "sessC", "logC", NOW_ISO, 1, "create", "Write",
                    div_path, body="# original ai content\n", tuid="t3", success=True, eligible=True),
]

# file-history index: snapshot of A's exact bytes (independent store) -> second signal
import json as _json
fh_dir = os.path.join(tmp, ".fh", "sessA")
os.makedirs(fh_dir)
snapfile = os.path.join(fh_dir, "abc123@v1")
open(snapfile, "w").write(ai_body)
fh_index = {ai_path: [{"session": "sessA", "version": 1, "snapshot_file": snapfile, "path": ai_path}]}

evidence = graph.build_path_evidence(events, fh_index, mark.read_bytes, mark.snap_bytes)
cls = {c["path"]: c for c in classify.classify_all(evidence, events)}

# QUARANTINE MODEL (v0.6): mark on ORIGIN. git/fh raise confidence, they don't gate.
check("A: AI-created, bytes unchanged -> MARK, HIGH confidence",
      cls[ai_path]["action"] == "mark" and cls[ai_path]["confidence"] == "high"
      and cls[ai_path]["marker_type"] == "ai-origin")
check("B: human-base AI-edit -> report-only (mixed_authorship), NEVER marked",
      cls[human_path]["action"] == "report-only" and cls[human_path]["klass"] == "mixed_authorship")
check("C: AI-created but diverged on disk -> MARK, MEDIUM confidence (origin still AI)",
      cls[div_path]["action"] == "mark" and cls[div_path]["confidence"] == "medium")

# git/fh are confidence annotations, not gates: A marks even with no fh and non-git
evidence2 = graph.build_path_evidence(events, {}, mark.read_bytes, mark.snap_bytes)
cls2 = {c["path"]: c for c in classify.classify_all(evidence2, events)}
check("A without fh + non-git STILL marks (origin gate, recall-biased)",
      cls2[ai_path]["action"] == "mark" and cls2[ai_path]["confidence"] == "high")

# The real CLAUDE.md trap: human content, AI edited, disk == human base -> never mark
trap = os.path.join(tmp, "CLAUDE.md")
open(trap, "w").write("# Global standards\nhuman authored\n")
trap_events = [adapters._event("claude", "sX", "lX", "2026-06-01T09:00:00Z", 1, "edit", "Edit",
                               trap, edits=[{"old": "human authored", "new": "human authored extra"}],
                               tuid="tt", success=True, eligible=True)]
trap_ev = graph.build_path_evidence(trap_events, {}, mark.read_bytes, mark.snap_bytes)
trap_cls = classify.classify_all(trap_ev, trap_events)[0]
check("CLAUDE.md trap (human base, AI edit) -> never marked",
      trap_cls["action"] != "mark")

# git annotation: under VCS, A still marks (origin gate) and records git as a confidence signal
classify.in_vcs = lambda p: True
cls_vcs = {c["path"]: c for c in classify.classify_all(evidence2, events)}
check("A under VCS marks (origin) and notes git as a confidence signal",
      cls_vcs[ai_path]["action"] == "mark"
      and any("git" in s for s in cls_vcs[ai_path]["signals"]))
classify.in_vcs = lambda p: False  # restore non-git default for remaining checks


print("\n[reconciliation invariant — DESIGN §10]")
rep = report.build_report(list(cls.values()), {"log_counts": {}})
check("reconciliation balances", rep["balanced"] is True)


print("\n[marker round-trip + idempotency — DESIGN §7.3]")
session = "test-session-uuid"
# dry-run first
man, counts, rid = mark.apply_markers([cls[ai_path]], session, do_write=False)
check("dry-run does not write", counts.get("would-mark") == 1 and not provenance.is_marked(open(ai_path).read()))
# real write
man, counts, rid = mark.apply_markers([cls[ai_path]], session, do_write=True)
check("apply writes exactly one marker", counts.get("marked") == 1 and provenance.is_marked(open(ai_path).read()))
check("marker is creation-only ai-origin:backfilled", "ai-origin:backfilled" in open(ai_path).read())
# idempotent re-run
man2, counts2, rid2 = mark.apply_markers([cls[ai_path]], session, do_write=True)
check("re-run skips already-marked", counts2.get("already-marked") == 1)
# restore
mark.restore(rid)
check("restore round-trips to original bytes", open(ai_path).read() == ai_body)


print("\n[secret quarantine — DESIGN §7.1]")
check("glob quarantine (.env)", mark.quarantined_by_glob("/x/.env.local"))
check("content quarantine (AWS key prefix)",
      mark.quarantined_by_content(b"key = AKIAIOSFODNN7EXAMPLE1234567890ABCD"))
check("content quarantine (PEM)",
      mark.quarantined_by_content(b"-----BEGIN RSA PRIVATE KEY-----\nabc\n"))
check("normal code not quarantined", not mark.quarantined_by_content(ai_body.encode()))


print("\n[grammar drift guard — DESIGN §0]")
check("grammar recognizes ai-origin:backfilled", provenance.is_marked("x ai-origin:backfilled y"))
check("grammar still recognizes legacy ai:suggestion", provenance.is_marked("ai:suggestion"))
check("grammar_sha stable + nonempty", len(provenance.grammar_sha()) == 64)


print("\n[v0.6 safety net]")
# write-race: report-time content_sha must catch a file changed between report and apply
wr = os.path.join(tmp, "race.py")
open(wr, "w").write("# v1\n")
orig_sha = hashlib.sha256(b"# v1\n").hexdigest()
dec = {"path": wr, "confidence": "high", "content_sha": orig_sha,
       "origin_event": {"session": "s"}, "sessions": ["s"], "machine_reason": "x"}
open(wr, "w").write("# HUMAN REWROTE THIS\n")   # changed after report
_, c_wr, _ = mark.apply_markers([dec], "sess", do_write=True)
check("write-race: changed-since-report file is NOT marked",
      c_wr.get("changed-since-classify") == 1 and not provenance.is_marked(open(wr).read()))

# restore fail-loud on a missing backup blob
fl = os.path.join(tmp, "faillaud.md")
open(fl, "w").write("hello\n")
dec_fl = {"path": fl, "confidence": "high", "content_sha": hashlib.sha256(b"hello\n").hexdigest(),
          "origin_event": {"session": "s"}, "sessions": ["s"], "machine_reason": "x"}
_, _, rid_fl = mark.apply_markers([dec_fl], "sess", do_write=True)
os.remove(os.path.join(mark.BACKUP_ROOT, rid_fl, mark._bak_name(fl)))   # nuke the backup
check("restore fails loud (rc!=0) when a backup blob is missing", mark.restore(rid_fl) != 0)

# symlink + hardlink are skipped, never written through
tgt = os.path.join(tmp, "real_target.md"); open(tgt, "w").write("TARGET\n")
sym = os.path.join(tmp, "link.md"); os.symlink(tgt, sym)
dec_sym = {"path": sym, "confidence": "high", "content_sha": None,
           "origin_event": {"session": "s"}, "sessions": ["s"], "machine_reason": "x"}
_, c_sym, _ = mark.apply_markers([dec_sym], "sess", do_write=True)
check("symlink skipped, target untouched",
      c_sym.get("skip-symlink") == 1 and open(tgt).read() == "TARGET\n")
h1 = os.path.join(tmp, "h1.md"); open(h1, "w").write("HL\n")
h2 = os.path.join(tmp, "h2.md"); os.link(h1, h2)
dec_h = {"path": h2, "confidence": "high", "content_sha": None,
         "origin_event": {"session": "s"}, "sessions": ["s"], "machine_reason": "x"}
_, c_h, _ = mark.apply_markers([dec_h], "sess", do_write=True)
check("hardlinked file skipped", c_h.get("skip-hardlink") == 1)

# Codex per-call cwd: relative paths resolve against the cwd in effect AT each call
add1 = {"type": "custom_tool_call", "name": "apply_patch", "call_id": "c1",
        "input": "*** Begin Patch\n*** Add File: rel1.txt\n+hi\n*** End Patch"}
out1 = {"type": "custom_tool_call_output", "call_id": "c1", "output": "Success."}
add2 = {"type": "custom_tool_call", "name": "apply_patch", "call_id": "c2",
        "input": "*** Begin Patch\n*** Add File: rel2.txt\n+yo\n*** End Patch"}
out2 = {"type": "custom_tool_call_output", "call_id": "c2", "output": "Success."}
items = [(0, "", add1, "/wsA"), (1, "", out1, "/wsA"), (2, "", add2, "/wsB"), (3, "", out2, "/wsB")]
cev = {e["tuid"]: e for e in adapters._codex_emit_from_items(items, "csess", "log", {})}
check("codex cwd-at-call: c1 resolves under /wsA, c2 under /wsB (not final cwd)",
      cev["c1"]["path"] == "/wsA/rel1.txt" and cev["c2"]["path"] == "/wsB/rel2.txt")

# unmark is structural: own-line marker removed, marker sharing a content line preserved
um = os.path.join(tmp, "um.md")
open(um, "w").write("<!-- ai-origin:backfilled | session:s -->\nreal content\nsee ai-origin:backfilled in this sentence\n")
mark.unmark(um, "sess", do_write=True)
um_txt = open(um).read()
check("unmark removes own-line marker but keeps content line mentioning it",
      "real content" in um_txt and "in this sentence" in um_txt
      and not um_txt.startswith("<!-- ai-origin:backfilled"))

# cleanup
import shutil
shutil.rmtree(tmp, ignore_errors=True)

print(f"\n==== {len(PASS)} passed, {len(FAIL)} failed ====")
if FAIL:
    print("FAILURES:", FAIL)
    sys.exit(1)
sys.exit(0)
